// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Place struct {
	ID                 string
	Name               string
	Rating             float64
	WeightedRating     float64
	UserRatingCount    int32
	Summary            pgtype.Text
	LastScraped        pgtype.Timestamp
	ImageUrl           pgtype.Text
	RecomputeStats     bool
	PrimaryType        pgtype.Text
	BusinessSummary    pgtype.Text
	PriceRange         pgtype.Int4
	EarliestReviewDate pgtype.Timestamp
	Lat                pgtype.Float8
	Lng                pgtype.Float8
}
