// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package config

import (
	"github.com/google/wire"
	"goodmeh/app/controller"
	"goodmeh/app/service"
)

// Injectors from injector.go:

func Initialize() *Initialization {
	healthController := controller.NewHealthController()
	placeService := service.NewPlaceService()
	placesController := controller.NewPlacesController(placeService)
	initialization := NewInitialization(healthController, placesController)
	return initialization
}

// injector.go:

var placeServiceSet = wire.NewSet(service.NewPlaceService, wire.Bind(new(service.IPlaceService), new(*service.PlaceService)))

var healthControllerSet = wire.NewSet(controller.NewHealthController, wire.Bind(new(controller.IHealthController), new(*controller.HealthController)))

var placesControllerSet = wire.NewSet(controller.NewPlacesController, wire.Bind(new(controller.IPlacesController), new(*controller.PlacesController)))
