name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test-and-build:
    if: "${{ github.event.pull_request.draft == false }}"
    name: Test and Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Sqlc
        uses: sqlc-dev/setup-sqlc@v3
        with:
          sqlc-version: "1.28.0"
      - run: sqlc diff

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.23.4"

      - name: Configure for private modules
        run: git config --global url."https://${{ secrets.GH_TOKEN }}@github.com/".insteadOf "https://github.com/"
      - run: go env -w GOPRIVATE=github.com/goodmeh/backend-private

      - name: Install dependencies
        run: go mod download

      # TODO: Enable once the tests are ready
      # - name: Run tests
      #   run: go test -v ./...

      - name: Build
        run: go build
